"use client";
import { useRef, useEffect } from "react";
import { motion } from "framer-motion";
import Image from "next/image";

const showcaseItems = [
  { before: "/showcase/before-1.jpg", after: "/showcase/after-1.jpg", label: "Silk Saree" },
  { before: "/showcase/before-2.jpg", after: "/showcase/after-2.jpg", label: "Cotton Kurta" },
  { before: "/showcase/before-3.jpg", after: "/showcase/after-3.jpg", label: "Lehenga" },
  { before: "/showcase/before-4.jpg", after: "/showcase/after-4.jpg", label: "Sherwani" },
  { before: "/showcase/before-5.jpg", after: "/showcase/after-5.jpg", label: "Anarkali" },
  { before: "/showcase/before-6.jpg", after: "/showcase/after-6.jpg", label: "Palazzo Set" },
];

function PlaceholderImage({ label, isAfter }: { label: string; isAfter: boolean }) {
  return (
    <div
      className={`w-full h-full flex flex-col items-center justify-center rounded-lg ${
        isAfter
          ? "bg-gradient-to-br from-indigo-900/60 to-violet-900/60"
          : "bg-gradient-to-br from-zinc-800 to-zinc-900"
      }`}
    >
      <div className="text-4xl mb-2">{isAfter ? "✨" : "👗"}</div>
      <div className="text-xs text-zinc-400 font-medium">{isAfter ? "On Model" : "Flat Lay"}</div>
      <div className="text-xs text-zinc-500 mt-1">{label}</div>
    </div>
  );
}

export function Showcase() {
  const sectionRef = useRef<HTMLElement>(null);
  const titleRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const loadGSAP = async () => {
      const gsap = (await import("gsap")).default;
      const { ScrollTrigger } = await import("gsap/ScrollTrigger");
      gsap.registerPlugin(ScrollTrigger);

      const ctx = gsap.context(() => {
        // Title
        gsap.fromTo(
          titleRef.current,
          { opacity: 0, y: 40 },
          { opacity: 1, y: 0, duration: 0.8, ease: "power4.out",
            scrollTrigger: { trigger: titleRef.current, start: "top 80%", once: true } }
        );

        // Cards stagger
        const cards = sectionRef.current?.querySelectorAll(".showcase-card");
        if (cards) {
          gsap.fromTo(
            cards,
            { opacity: 0, y: 40, scale: 0.95 },
            {
              opacity: 1, y: 0, scale: 1, duration: 0.6, stagger: 0.1, ease: "power3.out",
              scrollTrigger: { trigger: sectionRef.current, start: "top 70%", once: true },
            }
          );
        }
      }, sectionRef);

      return () => ctx.revert();
    };
    loadGSAP();
  }, []);

  return (
    <section ref={sectionRef} id="showcase" className="py-32 bg-[#0A0A0A]">
      <div className="max-w-7xl mx-auto px-6">
        <div className="text-center mb-16">
          <div ref={titleRef} className="font-display text-4xl md:text-5xl font-bold text-white mb-4">
            See the Magic
          </div>
          <p className="text-zinc-500 text-lg">
            Real garments. Real results. All generated by AI.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {showcaseItems.map((item, i) => (
            <motion.div
              key={i}
              className="showcase-card group relative rounded-2xl overflow-hidden bg-zinc-900 border border-white/5 cursor-pointer"
              whileHover={{ y: -4, borderColor: "rgba(99,102,241,0.3)" }}
              transition={{ duration: 0.2 }}
            >
              <div className="flex h-56">
                <div className="w-1/2 relative overflow-hidden">
                  <PlaceholderImage label={item.label} isAfter={false} />
                  <div className="absolute inset-0" />
                </div>
                <div className="w-px bg-white/10" />
                <div className="w-1/2 relative overflow-hidden">
                  <PlaceholderImage label={item.label} isAfter={true} />
                </div>
              </div>
              <div className="p-4 flex items-center justify-between">
                <span className="text-white font-medium text-sm">{item.label}</span>
                <span className="text-xs text-indigo-400 font-medium bg-indigo-400/10 px-2 py-1 rounded-full">
                  AI Generated
                </span>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
